#ifndef TRACK_ROUND_H
#define TRACK_ROUND_H

// Define M_PI if not used elsewhere before this include
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// --- Rounded Corner Track Dimensions ---
#define ROUND_TRACK_MAIN_WIDTH 80.0f
#define ROUND_TRACK_MAIN_LENGTH 120.0f
#define ROUND_TRACK_ROAD_WIDTH 12.0f
#define ROUND_CORNER_RADIUS (ROUND_TRACK_ROAD_WIDTH * 1.8f) // Centerline radius
#define ROUND_HALF_ROAD_WIDTH (ROUND_TRACK_ROAD_WIDTH / 2.0f)
#define ROUND_INNER_CORNER_RADIUS (ROUND_CORNER_RADIUS - ROUND_HALF_ROAD_WIDTH)
#define ROUND_OUTER_CORNER_RADIUS (ROUND_CORNER_RADIUS + ROUND_HALF_ROAD_WIDTH)
#define ROUND_STRAIGHT_X_LIMIT (ROUND_TRACK_MAIN_WIDTH / 2.0f - ROUND_CORNER_RADIUS)
#define ROUND_STRAIGHT_Z_LIMIT (ROUND_TRACK_MAIN_LENGTH / 2.0f - ROUND_CORNER_RADIUS)
#define ROUND_CORNER_CENTER_TR_X (ROUND_STRAIGHT_X_LIMIT)
#define ROUND_CORNER_CENTER_TR_Z (ROUND_STRAIGHT_Z_LIMIT)
#define ROUND_CORNER_CENTER_TL_X (-ROUND_STRAIGHT_X_LIMIT)
#define ROUND_CORNER_CENTER_TL_Z (ROUND_STRAIGHT_Z_LIMIT)
#define ROUND_CORNER_CENTER_BL_X (-ROUND_STRAIGHT_X_LIMIT)
#define ROUND_CORNER_CENTER_BL_Z (-ROUND_STRAIGHT_Z_LIMIT)
#define ROUND_CORNER_CENTER_BR_X (ROUND_STRAIGHT_X_LIMIT)
#define ROUND_CORNER_CENTER_BR_Z (-ROUND_STRAIGHT_Z_LIMIT)
// Finish line placed on right straight for consistency
#define ROUND_FINISH_LINE_X_START (ROUND_TRACK_MAIN_WIDTH / 2.0f - ROUND_HALF_ROAD_WIDTH)
#define ROUND_FINISH_LINE_X_END   (ROUND_TRACK_MAIN_WIDTH / 2.0f + ROUND_HALF_ROAD_WIDTH)
#define ROUND_FINISH_LINE_THICKNESS 2.0f

// --- Common Values ---
#define CORNER_SEGMENTS 20      // Segments per 90-degree corner
#define FINISH_LINE_Z 0.0f
#define COLLISION_EPSILON 0.2f

// --- Function Declarations ---
void renderRoundTrack();
void renderRoundGuardrails();
int isPositionOnRoundTrack(float x, float z);

#endif // TRACK_ROUND_H